### ISSUE TITLE
Add John.Whitlock to pypi package maintainers

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/django-tidings#28]
I would like to be able to release the current master to PyPI. I need an existing owner of [django-tidings on PyPI](https://pypi.python.org/pypi/django-tidings) to add John.Whitlock to the owners or maintainers lists.

My plans are:

* Add additional Makefile commands for package releases (similar to [django-dnt](https://github.com/mozilla/django-dnt/blob/master/Makefile))
* Release version 1.2 (adding Django 1.8 and Python 3 support)
* Drop support for Django 1.7 and earlier, and for [South](http://south.readthedocs.io/en/latest/).
* Add support for Django 1.9, 1.10, and 1.11
* Fix #26 (increase email field to 254 characters)
* Release as version 1.3

**Comment by willkg** [comment]
@erikrose @jezdez I'm not an owner of the PyPI record--but you two are. Can one of you help @jwhitlock?

**Comment by jezdez** [comment]
@willkg Just added @jwhitlock as maintainer on PyPI. Since this app would fit the bill nicely, may I suggest to transfer it to Jazzband?

**Comment by willkg** [comment]
Does it really fit in with other jazzband projects? As near as I can tell, MDN is the only real user of django-tidings (now that SUMO is gone).

**Comment by jezdez** [comment]
@willkg PyPI doesn't provide download stats anymore, so I'm not sure how many users out there exist. But in general it's okay to move things to Jazzband, if they follow the guidelines, like having docs, CI etc. BUT, I just rand the query against PyPI's BigQuery dataset and the results asking for downloads is:

```
[
  {
    "total_downloads": "769"
  }
]
```

So you may be right, that this is out of scope of Jazzband :)

**Comment by willkg** [comment]
I checked depsy.org, did a search on github for "django-tidings" and looked at the download stats. That's definitely not perfect, but it's probably a "good enough" proxy.

I wrote a blog post about this because it comes up often:

http://bluesock.org/~willkg/blog/dev/who_uses_my_stuff.html

If there are other ways of figuring out "who uses this thing", I'm all ears.

**Comment by jwhitlock** [comment]
I was able to upload [django-tidings 1.2](https://pypi.python.org/pypi/django-tidings). Thanks for adding me!

I'll continue toward a version 1.3. More PRs to come...

**Comment by erikrose** [comment]
Welcome, John!
