### ISSUE TITLE
Fix Read The Docs integration / webhook

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/django-tidings#47]
The documentation is no longer updating on merges to master:

https://django-tidings.readthedocs.io/en/latest/

A RTD admin needs to enable the integration:

* https://readthedocs.org/projects/django-tidings/ 
* https://docs.readthedocs.io/en/stable/webhooks.html

and then a GitHub admin needs to setup the web hook.

**Comment by erikrose** [comment]
I'm in the RTD admin interface, and everything looks enabled and green to me. I do see it's using Python 2.x to build the docs venv, so we'll want to change that sometime. Give me your RTD username and I'll make you an admin as well.

**Comment by jwhitlock** [comment]
@erikrose thanks! I'm jwhitlock on RTD.

**Comment by erikrose** [comment]
I believe I've got it working now. I had to "re-sync" the web hook on RTD's end, whatever that means.

**Comment by jwhitlock** [comment]
The latest docs are now published. I'll work on the Python 3 switch etc. Thanks, @erikrose!

**Comment by erikrose** [comment]
Thanks for all your work keeping this thing up to date! :-D
