### ISSUE TITLE
Allow mapping from Watches back to Events

### ISSUE THREAD

**Issue by erikrose** [mozilla/django-tidings#6]
Stick a metaclass on Events to register them. Then we can move things like Event.description_of_watch(watch) onto Watch itself, a more natural spelling. It also gives us a more natural way to test what Event a Watch coming out of an EventUnion refers to.

**Comment by jwhitlock** [comment]
We're preparing to archive the project (issue https://github.com/mozilla/django-tidings/issues/52), and will not take on this work.
